version: 2.1

orbs:
  docker: circleci/docker@2.0.1

jobs:
  build:
    working_directory: ~/terraria
    docker:
      - image: cimg/base:2022.01
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker image
          command: docker build -t ghcr.io/asemlef/terraria .
      - run:
          name: Save image to cache
          command: docker save -o ~/terraria/app.tar ghcr.io/asemlef/terraria
      - persist_to_workspace:
          root: .
          paths: app.tar

  test:
    working_directory: ~/terraria
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Import docker image
          command: docker load -i "$PWD/app.tar"
      - run:
          name: Run tests
          command: |
            docker run -id --volume "$PWD/.circleci/World.wld:/data/Worlds/World.wld" --name terraria ghcr.io/asemlef/terraria
            sleep 10; docker exec terraria nc -z localhost 7777
      - run:
          name: Capture logs
          command: docker logs terraria > terraria.log
          when: always  # this will run even if other steps fail
      - store_artifacts:
          path: ~/terraria/terraria.log

  deploy:
    docker:
      - image: cimg/base:2022.01
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Check that this is the latest commit
          command: |
            LATEST_COMMIT=$(git ls-remote $CIRCLE_REPOSITORY_URL | grep $CIRCLE_BRANCH | cut -f 1)
            LAST_COMMIT_DATETIME=$(git show --format="%ct" $LATEST_COMMIT | head -n 1)
            BUILD_COMMIT_DATETIME=$(git show --format="%ct" $CIRCLE_SHA1 | head -n 1)
            if [ "$LAST_COMMIT_DATETIME" -gt "$BUILD_COMMIT_DATETIME" ]; then
              echo "more recent commit to branch, exiting"
              exit 1
            fi
      - run:
          name: Import docker image
          command: docker load -i "$PWD/app.tar"
      - run:
          name: Upload docker image
          command: |
            echo "$GHCR_PAT" | docker login ghcr.io -u asemlef --password-stdin
            docker push ghcr.io/asemlef/terraria:latest

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - hold
